# Generated by Django 4.1.7 on 2023-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_imgage',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
